name: teste pessoa

on: [push]

jobs: 
  build:

    runs-on: ubuntu-latest

    steps: 
    - name: setup github actions
      uses: actions/setup-python@v2
    
    - name: Setup Python 3.11
      uses: actions 
      with:
        python-version: '3.*'

    - name: Run test
      run: python -m unittest python.yaml